/**
 * Options for creating a new {@link Run} via the builder pattern.
 *
 * Every field is optional — sensible defaults are applied automatically.
 *
 * @example
 * ```ts
 * const r = run({ sessionId: "sess_123", conversational: true });
 * ```
 */
export type RunOptions = {
  /** Custom run identifier. Defaults to a random UUID. */
  runId?: string;
  /**
   * Group multiple runs into a logical session (e.g. a single user
   * conversation). Runs sharing a `sessionId` appear together in the
   * dashboard timeline.
   */
  sessionId?: string;
  /**
   * Mark this run as part of a multi-turn conversation. When `true`,
   * the dashboard links sequential runs in the same session as a
   * continuous thread.
   */
  conversational?: boolean;
  /** Override the run start time. Defaults to `new Date()`. */
  startTime?: Date;
  /**
   * Auto-flush timeout in milliseconds. If the run is not ended within
   * this duration, it will be automatically flushed with an error status.
   *
   * Set to `0` to disable. Can also be set globally via
   * {@link ClientConfig.runTimeout | configure({ runTimeout })}.
   *
   * @defaultValue `1_200_000` (20 minutes)
   */
  timeout?: number;
};

/**
 * Options for creating a new {@link Step} via `run.step()`.
 *
 * @example
 * ```ts
 * const s = r.step({ stepId: "step_abc" });
 * ```
 */
export type StepOptions = {
  /** Custom step identifier. Defaults to a random UUID. */
  stepId?: string;
  /** Override the step start time. Defaults to `new Date()`. */
  startTime?: Date;
};

/**
 * Options for creating a new {@link ToolCall} via `run.toolCall()`.
 *
 * @example
 * ```ts
 * const tc = r.toolCall({ name: "search", toolCallId: "tc_xyz" });
 * ```
 */
export type ToolCallOptions = {
  /** Custom tool call identifier. Defaults to a random UUID. */
  toolCallId?: string;
  /** The name of the tool being invoked (e.g. `"search"`, `"get_weather"`). */
  name?: string;
  /** Override the tool call start time. Defaults to `new Date()`. */
  startTime?: Date;
};

/**
 * Token usage breakdown for a single LLM step.
 *
 * All fields are optional — report whichever counts your provider exposes.
 *
 * @example
 * ```ts
 * s.tokens({ uncached: 120, cached: 30, completion: 45 });
 * ```
 */
export type TokenUsage = {
  /** Number of prompt tokens that were **not** served from cache. */
  uncached?: number;
  /** Number of prompt tokens served from cache (e.g. prompt caching). */
  cached?: number;
  /** Number of tokens generated by the model in the completion. */
  completion?: number;
};

/**
 * Specifies which model was used for an LLM step.
 *
 * Pass a plain string when the requested and actually-used model are the same.
 * Use the object form when they differ (e.g. requesting `"gpt-4o"` but the
 * provider routes to a specific snapshot like `"gpt-4o-2024-08-06"`).
 *
 * @example
 * ```ts
 * // Shorthand — same model for both
 * s.model("gpt-4o");
 *
 * // Explicit requested vs. used
 * s.model({ requested: "gpt-4o", used: "gpt-4o-2024-08-06" });
 * ```
 */
export type ModelConfig = string | { requested?: string; used?: string };

// ---------------------------------------------------------------------------
// Factory inputs — used with sendRun / sendStep / sendToolCall
// ---------------------------------------------------------------------------

/**
 * Complete run data for the factory function {@link sendRun}.
 *
 * Use this when all data is already available (post-hoc logging, batch
 * imports, replaying from logs).
 *
 * @example
 * ```ts
 * await sendRun({
 *   prompt: "What's the weather?",
 *   response: "72°F in SF",
 *   startTime: new Date("2025-01-01T00:00:00Z"),
 *   endTime:   new Date("2025-01-01T00:00:01Z"),
 *   steps: [{ prompt: "...", response: "...", model: "gpt-4o", ... }],
 * });
 * ```
 */
export type RunInput = {
  /** Custom run identifier. Defaults to a random UUID. */
  runId?: string;
  /** Session identifier to group related runs. */
  sessionId?: string;
  /** Whether this run is part of a multi-turn conversation. */
  conversational?: boolean;
  /** The user prompt / input that initiated the run. */
  prompt: string;
  /** The agent's final response. */
  response?: string;
  /** When the run started (ISO-8601 string or `Date`). */
  startTime: Date | string;
  /** When the run finished (ISO-8601 string or `Date`). */
  endTime: Date | string;
  /**
   * Outcome status code.
   * - `0` — success (default)
   * - `2` — error
   */
  statusCode?: number;
  /** Human-readable status / error message. */
  statusMessage?: string;
  /** Arbitrary key-value metadata attached to the run. */
  metadata?: Record<string, string>;
  /** LLM steps that occurred during the run. */
  steps?: StepInput[];
  /** Tool calls that occurred during the run. */
  toolCalls?: ToolCallInput[];
};

/**
 * Complete step data for the factory function {@link sendStep}.
 *
 * A step represents a single LLM invocation within a run.
 */
export type StepInput = {
  /**
   * The parent run identifier. Required when sending a step independently
   * via {@link sendStep}; optional when nesting inside {@link RunInput.steps}.
   */
  runId?: string;
  /** Custom step identifier. Defaults to a random UUID. */
  stepId?: string;
  /** The prompt sent to the LLM. */
  prompt: string;
  /** The LLM's response. */
  response: string;
  /** When the step started (ISO-8601 string or `Date`). */
  startTime: Date | string;
  /** When the step finished (ISO-8601 string or `Date`). */
  endTime: Date | string;
  /**
   * Outcome status code.
   * - `0` — success (default)
   * - `2` — error
   */
  statusCode?: number;
  /** Human-readable status / error message. */
  statusMessage?: string;
  /** Which model was used. See {@link ModelConfig}. */
  model?: ModelConfig;
  /** The model's finish/stop reason (e.g. `"stop"`, `"length"`, `"tool_calls"`). */
  finishReason?: string;
  /** Token usage breakdown. See {@link TokenUsage}. */
  tokens?: TokenUsage;
  /** Actual cost of this step in USD. */
  cost?: number;
  /**
   * The tool definitions / function schemas that were available to the model
   * during this step. Pass a JSON string or an array (auto-serialized).
   */
  toolDefinitions?: string | unknown[];
};

/**
 * Complete tool call data for the factory function {@link sendToolCall}.
 *
 * A tool call represents a single tool/function invocation within a run.
 */
export type ToolCallInput = {
  /**
   * The parent run identifier. Required when sending a tool call independently
   * via {@link sendToolCall}; optional when nesting inside {@link RunInput.toolCalls}.
   */
  runId?: string;
  /** Custom tool call identifier. Defaults to a random UUID. */
  toolCallId?: string;
  /** The name of the tool that was invoked (e.g. `"search"`, `"get_weather"`). */
  name: string;
  /** When the tool call started (ISO-8601 string or `Date`). */
  startTime: Date | string;
  /** When the tool call finished (ISO-8601 string or `Date`). */
  endTime: Date | string;
  /**
   * Outcome status code.
   * - `0` — success (default)
   * - `2` — error
   */
  statusCode?: number;
  /** Human-readable status / error message. */
  statusMessage?: string;
  /** Arguments passed to the tool. Pass a string or object (auto-serialized). */
  args?: string | Record<string, unknown>;
  /** Return value from the tool. Pass a string or object (auto-serialized). */
  result?: string | Record<string, unknown>;
};

/**
 * Global SDK configuration. Pass to {@link configure} to set options
 * that apply to all runs.
 *
 * @example
 * ```ts
 * import { configure } from "@contextcompany/custom";
 *
 * configure({
 *   apiKey: "your_api_key",
 *   debug: true,
 * });
 * ```
 */
export type ClientConfig = {
  /**
   * API key for authentication. Overrides the `TCC_API_KEY` environment
   * variable. Keys starting with `"dev_"` automatically route to the
   * development ingestion endpoint.
   */
  apiKey?: string;
  /**
   * Enable debug logging to the console. Overrides the `TCC_DEBUG`
   * environment variable.
   */
  debug?: boolean;
  /** Custom ingestion endpoint URL. Overrides the `TCC_URL` environment variable. */
  url?: string;
  /**
   * Default auto-flush timeout (in ms) for all new runs. Can be overridden
   * per-run via {@link RunOptions.timeout}.
   *
   * @defaultValue `1_200_000` (20 minutes)
   */
  runTimeout?: number;
};
